// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXJHRLYuJAUkzb5cw6KvFvAf0ktulQ2Q',
    appId: '1:608857058872:web:8c2c5a4d8f69eb6a4c80cd',
    messagingSenderId: '608857058872',
    projectId: 'boomer-cee36',
    authDomain: 'boomer-cee36.firebaseapp.com',
    storageBucket: 'boomer-cee36.appspot.com',
    measurementId: 'G-31XTHDT47J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC129oGr2d423pZRqwef6L_qgetV89IGCI',
    appId: '1:608857058872:android:bfffd12b93aba91c4c80cd',
    messagingSenderId: '608857058872',
    projectId: 'boomer-cee36',
    storageBucket: 'boomer-cee36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhjMGxz8IhjOl-ZUB6hb7R0Qye9qbzpO4',
    appId: '1:608857058872:ios:1174c54791ac8a354c80cd',
    messagingSenderId: '608857058872',
    projectId: 'boomer-cee36',
    storageBucket: 'boomer-cee36.appspot.com',
    iosClientId: '608857058872-rv1ilkig14cc4qibl12hutvkf1o9kvkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhjMGxz8IhjOl-ZUB6hb7R0Qye9qbzpO4',
    appId: '1:608857058872:ios:1174c54791ac8a354c80cd',
    messagingSenderId: '608857058872',
    projectId: 'boomer-cee36',
    storageBucket: 'boomer-cee36.appspot.com',
    iosClientId: '608857058872-rv1ilkig14cc4qibl12hutvkf1o9kvkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomer',
  );
}
